version : '3'

services :
  app: 
    build:
        context : .
        dockerfile : Dockerfile
    ports :
        - "127.0.0.1:8800:8800" # Map local port to container port
    env_file:
        - .env        
